version: "2.0"
services:
  srv:
    build: .
    image: registry.it-expert.com.ua/nexus/privat-manager:1.1.2
    volumes:
      - ./resources/settings:/app/resources/settings
    ports:
      - 3000:3000
